# name: Git Hello
# on:
#   pull_request:
#     paths:
#       - "!**.md"
#       - "!.github/workflows/*"
#       - "**.txt"
#   workflow_dispatch:
# jobs:
#   main:
#     runs-on: ubuntu-last
#     steps:
#       - uses: actions/checkout@v2
#       - name: Hello World
#         run: |
#           echo "Hello World"